name: ✨ Feature
description: 새로운 기능 아이디어가 있나요?
title: '[feat] '
labels: ['✨ feat']
body:
  - type: textarea
    id: summary
    attributes:
      label: 기능 요약
      description: 추가하고 싶은 기능을 간단히 설명해주세요.

  - type: textarea
    id: details
    attributes:
      label: 기능 설명
      description: 어떤 상황에서 어떤 기능이 필요했는지 구체적으로 작성해주세요.
